name: CI/CD to Docker Hub

on:
  push:
    branches: [ "main" ]
  tags:
    - 'v*.*.*'  # Trigger on version tags like v1.0.0

env:
  DOCKERHUB_USERNAME: vanbassum
  IMAGE_NAME: poen

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Setup Docker Buildx
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    # Login to Docker Hub
    - name: DockerHub Login
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    # Extract metadata for the Docker image
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v1
      with:
        images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}

    # Get short SHA for tagging
    - name: Get short SHA
      id: sha
      run: echo "::set-output name=sha::$(echo ${GITHUB_SHA} | cut -c1-7)"

    # Build and push Docker image
    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.sha.outputs.sha }}
